Repository pixl-os/pegasus-frontend, pull requests merged in 2022-11, with the labels that each got.

#19 Feat option change setting menu color
  CHANGELOG.md
  src/backend/model/internal/settings/ParametersList.cpp
  src/frontend/main.qml
  src/frontend/menu/settings/InterfaceMain.qml
Labels: enhancement

#20 add PS5 controller layout
  CHANGELOG.md
  src/frontend/assets/gamepad/ps5/a_ps5.png
  src/frontend/assets/gamepad/ps5/b_ps5.png
  src/frontend/assets/gamepad/ps5/base_ps5.png
  src/frontend/assets/gamepad/ps5/dpad_ps5.png
  src/frontend/assets/gamepad/ps5/dpdown_ps5.png
  src/frontend/assets/gamepad/ps5/dpleft_ps5.png
  src/frontend/assets/gamepad/ps5/dpright_ps5.png
  src/frontend/assets/gamepad/ps5/dpup_ps5.png
  src/frontend/assets/gamepad/ps5/guide_ps5.png
  src/frontend/assets/gamepad/ps5/l1_ps5.png
  src/frontend/assets/gamepad/ps5/l2_ps5.png
  src/frontend/assets/gamepad/ps5/lstick_ps5.png
  src/frontend/assets/gamepad/ps5/r1_ps5.png
  src/frontend/assets/gamepad/ps5/r2_ps5.png
  src/frontend/assets/gamepad/ps5/rstick_ps5.png
  src/frontend/assets/gamepad/ps5/select_ps5.png
  src/frontend/assets/gamepad/ps5/start_ps5.png
  src/frontend/assets/gamepad/ps5/x_ps5.png
  src/frontend/assets/gamepad/ps5/y_ps5.png
  src/frontend/frontend.qrc
  src/frontend/main.qml
  src/frontend/menu/settings/GamepadEditor.qml
Labels: enhancement

#22 add update online shinretro
  CHANGELOG.md
  src/frontend/main.qml
Labels: enhancement

#21 feat(xboxone): add this controller
  CHANGELOG.md
  src/frontend/assets/gamepad/xboxone/a_xboxone.png
  src/frontend/assets/gamepad/xboxone/b_xboxone.png
  src/frontend/assets/gamepad/xboxone/base_xboxone.png
  src/frontend/assets/gamepad/xboxone/dpad_xboxone.png
  src/frontend/assets/gamepad/xboxone/guide_xboxone.png
  src/frontend/assets/gamepad/xboxone/l1_xboxone.png
  src/frontend/assets/gamepad/xboxone/l2_xboxone.png
  src/frontend/assets/gamepad/xboxone/lstick_xboxone.png
  src/frontend/assets/gamepad/xboxone/r1_xboxone.png
  src/frontend/assets/gamepad/xboxone/r2_xboxone.png
  src/frontend/assets/gamepad/xboxone/rstick_xboxone.png
  src/frontend/assets/gamepad/xboxone/select_xboxone.png
  src/frontend/assets/gamepad/xboxone/share_xboxone.png
  src/frontend/assets/gamepad/xboxone/start_xboxone.png
  src/frontend/assets/gamepad/xboxone/x_xboxone.png
  src/frontend/assets/gamepad/xboxone/y_xboxone.png
  src/frontend/frontend.qrc
  src/frontend/main.qml
  src/frontend/menu/settings/GamepadEditor.qml
Labels: enhancement

#24 fix(parameterList): fix bad value for video settings and color interface
  src/frontend/menu/settings/InterfaceMain.qml
  src/frontend/menu/settings/VideoSettings.qml
  src/frontend/menu/settings/common/DetailedButton.qml
  src/frontend/menu/settings/common/SimpleButton.qml
Labels: bug

#26 fix(changelog): update nomenclature
  CHANGELOG.md
Labels: documentation

#27 fix(sdl): force loading of SDL user mappings during start
  CHANGELOG.md
  src/backend/model/internal/GamepadManagerSDL2.cpp
Labels: bug

#28 fix(layout): add default value in layout and selection of x configfield
  CHANGELOG.md
  src/frontend/menu/settings/GamepadEditor.qml
Labels: bug
